name: my_flyn
description: A Flutter application based on the Figma design.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get: ^4.6.5  # GetX for state management
  permission_handler: ^10.2.0  # For handling permissions
  shared_preferences: ^2.1.0  # For local storage
  flutter_svg: ^2.0.5  # For SVG support
  cached_network_image: ^3.2.3  # For image caching
  intl: ^0.18.0  # For internationalization

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700